
/**************************************************************
 *	
 *	chaseMusic, 8 bit, 11025Hz,
 *	1 channel, 1524639 bytes/channel
 *	Total Size: 1 * 1524639 + 4 (header) = 1524683 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/madisonhoover/Desktop/gba-programming/M03_MadisonHoover copy/chaseMusic.wav
 *	Time-stamp: Mon Nov 18 13:51:38 2019
 *	
 **************************************************************/

#ifndef __CHASEMUSICH__
#define __CHASEMUSICH__

#define CHASEMUSICFREQ 11025
#define CHASEMUSICLEN 1524639

extern const unsigned char chaseMusic[1524639];

#endif /* __CHASEMUSICH__ */
