
/**************************************************************
 *	
 *	MarioPowerup, 8 bit, 11025Hz,
 *	1 channel, 22050 bytes/channel
 *	Total Size: 1 * 22050 + 4 (header) = 22094 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/madisonhoover/Desktop/gba-programming/FinalProject_MadisonHoover/MarioPowerup.wav
 *	Time-stamp: Mon Dec 02 11:09:11 2019
 *	
 **************************************************************/

#ifndef __MARIOPOWERUPH__
#define __MARIOPOWERUPH__

#define MARIOPOWERUPFREQ 11025
#define MARIOPOWERUPLEN 22050

extern const unsigned char MarioPowerup[22050];

#endif /* __MARIOPOWERUPH__ */
