
/**************************************************************
 *	
 *	mlg_airhorn, 8 bit, 11025Hz,
 *	1 channel, 33408 bytes/channel
 *	Total Size: 1 * 33408 + 4 (header) = 33452 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/madisonhoover/Desktop/gba-programming/M04_MadisonHoover/mlg-airhorn.wav
 *	Time-stamp: Mon Dec 02 09:23:05 2019
 *	
 **************************************************************/

#ifndef __MLG_AIRHORNH__
#define __MLG_AIRHORNH__

#define MLG_AIRHORNFREQ 11025
#define MLG_AIRHORNLEN 33408

extern const unsigned char mlg_airhorn[33408];

#endif /* __MLG_AIRHORNH__ */
