
/**************************************************************
 *	
 *	OriginalGameMusic, 8 bit, 11025Hz,
 *	1 channel, 44753 bytes/channel
 *	Total Size: 1 * 44753 + 4 (header) = 44797 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/madisonhoover/Desktop/gba-programming/M03_MadisonHoover copy/OriginalGameMusic.wav
 *	Time-stamp: Mon Nov 18 13:36:55 2019
 *	
 **************************************************************/

#ifndef __ORIGINALGAMEMUSICH__
#define __ORIGINALGAMEMUSICH__

#define ORIGINALGAMEMUSICFREQ 11025
#define ORIGINALGAMEMUSICLEN 44753

extern const unsigned char OriginalGameMusic[44753];

#endif /* __ORIGINALGAMEMUSICH__ */
