
/**************************************************************
 *	
 *	Slap_SoundMaster13_49669815, 8 bit, 11025Hz,
 *	1 channel, 14848 bytes/channel
 *	Total Size: 1 * 14848 + 4 (header) = 14892 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/madisonhoover/Desktop/gba-programming/M04_MadisonHoover/Slap-SoundMaster13-49669815.wav
 *	Time-stamp: Mon Nov 25 13:50:17 2019
 *	
 **************************************************************/

#ifndef __SLAP_SOUNDMASTER13_49669815H__
#define __SLAP_SOUNDMASTER13_49669815H__

#define SLAP_SOUNDMASTER13_49669815FREQ 11025
#define SLAP_SOUNDMASTER13_49669815LEN 14848

extern const unsigned char Slap_SoundMaster13_49669815[14848];

#endif /* __SLAP_SOUNDMASTER13_49669815H__ */
