
/**************************************************************
 *	
 *	startMusic, 8 bit, 11025Hz,
 *	1 channel, 2510208 bytes/channel
 *	Total Size: 1 * 2510208 + 4 (header) = 2510252 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/madisonhoover/Desktop/gba-programming/FinalProject_MadisonHoover/startMusic.wav
 *	Time-stamp: Mon Dec 02 11:27:00 2019
 *	
 **************************************************************/

#ifndef __STARTMUSICH__
#define __STARTMUSICH__

#define STARTMUSICFREQ 11025
#define STARTMUSICLEN 2510208

extern const unsigned char startMusic[2510208];

#endif /* __STARTMUSICH__ */
